name: washryte
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Contains utility classes in the style of
  # dart:async to work with asynchronous computations.
  async: any
  # Better conversion of ENUMs to string.
  # Dart has annoying EnumName.ValueName syntax when calling enum.toString, this package fixes that.
  enum_to_string: ^2.0.1
  # RxDart extends the capabilities of Dart Streams and StreamControllers.
  rxdart: ^0.27.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  # Draw SVG files on a Flutter Widget.
  # flutter_svg: ^0.23.0+1
  ###
  ### Firebase Packages ###
  ###
  firebase_core: ^1.10.0
  # A Flutter plugin to use the Google Analytics for Firebase API.
  firebase_analytics: ^8.3.4
  # Crashlytics helps you to collect analytics and
  # details about crashes and errors that occur in your app.
  firebase_crashlytics: ^2.3.0
  # Google services & Authentication
  google_sign_in: ^5.2.1
  # Flutter bridge to initiate Sign in with Apple (on iOS, macOS, and Android).
  # Includes support for keychain entries as well as signing in with an Apple ID.
  sign_in_with_apple: ^3.2.0
  # Customize App font
  google_fonts: ^2.1.0
  # This plugin allows Flutter apps to discover network connectivity
  # and configure themselves accordingly.
  connectivity: ^3.0.6
  # Check Internet connectivity
  internet_connection_checker: ^0.0.1+3
  # Service locator
  get_it: ^7.2.0
  # Flutter Platform Widgets
  flutter_platform_widgets: ^1.11.0
  # A powerful Http client for Dart, which supports Interceptors,
  # Global configuration, FormData, Request Cancellation, File downloading, Timeout etc.
  dio: ^4.0.4
  # Pretty Dio logger is a Dio interceptor that logs network calls in a pretty, easy to read format.
  pretty_dio_logger: ^1.1.1
  # Dio HTTP cache interceptor with multiple stores respecting HTTP directives (or not).
  dio_cache_interceptor: ^3.0.3
  # Flutter BloC for state management
  flutter_bloc: ^8.0.0
  # Automatically persists and restores bloc states
  hydrated_bloc: ^8.0.0
  # Custom event transformers inspired by ember concurrency.
  # Built to be used with the bloc state management package.
  bloc_concurrency: ^0.2.0
  # A lightweight and blazing fast key-value database written in pure Dart.
  hive_flutter: ^1.1.0
  # Provides:
  # - Immutable value types
  # - EnumClass, classes that behave like enums
  # - JSON serialization
  built_value: ^8.1.3
  # Provides: Immutable collections
  built_collection: ^5.1.1
  # Functional Programming
  dartz: ^0.10.0
  # For regular Unions
  freezed_annotation: ^1.0.0
  # For generating unique UUIDs
  uuid: ^3.0.5
  # Flutter widget that automatically resizes text to fit perfectly within its bounds
  auto_size_text: ^3.0.0-nullsafety.0
  # simplifies dependency injection
  injectable: ^1.5.0
  # provides internationalization
  # and localization facilities
  intl: ^0.17.0
  # A declarative routing solution
  auto_route: ^3.1.3
  # A collection of loading indicators animated with flutter.
  flutter_spinkit: ^5.1.0
  # Shimmer Skeleton Library.
  shimmer: ^2.0.0
  # Now this toast library supports two kinds of toast messages:
  # - one which requires BuildContext
  # - other with No BuildContext
  fluttertoast: ^8.0.8
  # Wraps platform-specific persistent storage for simple data
  shared_preferences: ^2.0.9
  # A Flutter plugin for finding commonly used locations on the filesystem.
  path_provider: ^2.0.7
  # A port of Kotlin's Kotlin Standard library for Dart/Flutter projects.
  kt_dart: ^0.10.0
  # A port of the Rails/ActiveSupport inflector library to Dart.
  inflection3: ^0.5.3+2
  # Customizable animated page indicator with a set of built-in effects.
  smooth_page_indicator: ^1.0.0+2
  # Defines the annotations used by json_serializable
  # to create code for JSON serialization and deserialization.
  json_annotation: ^4.3.0
  # retrofit.dart is a type conversion dio client generator
  # using source_gen and inspired by Chopper and Retrofit.
  retrofit: ^3.0.0
  # Floor provides a neat SQLite abstraction for your Flutter applications
  # inspired by the Room persistence library.
  floor: ^1.2.0
  # Use this package if you need more customization when notifying your user.
  another_flushbar: ^1.10.25
  # A simple API to format dates.
  date_format: ^2.0.4
  # A flutter library to show images from the internet
  # and keep them in the cache directory.
  cached_network_image: ^3.1.0+1
  # Approximate how your app looks and performs on another device.
  # device_preview: ^1.0.0-alpha.15
  # A flutter package which provides a simple way to Showcase/Highlight your widgets step by step.
  showcaseview: ^1.1.3
  # A flutter plugin for adapting screen and font size.Let your UI
  # display a reasonable layout on different screen sizes!
  flutter_screenutil: ^5.0.0+2
  # A Flutter plugin for iOS and Android for picking images from the image library,
  # and taking new pictures with the camera.
  image_picker: ^0.8.4+4
  # Cupertino version of the stock Material ListTile in Flutter.
  # PS: This is not a pixel perfect interpretation of the iOS Human Interface Guidelines.
  cupertino_list_tile: ^0.2.0
  # Create awesome and powerful modal bottom sheets.
  modal_bottom_sheet: ^2.0.0
  # A Flutter widget that can be expanded or collapsed by the user.
  expandable: ^5.0.1
  # Show beautiful bottom sheet as confirmation dialog quickly and easily.
  sweetsheet: ^0.4.0
  # This repository is an unofficial conversion of the Lottie-android library in pure Dart.
  lottie: ^1.2.1
  # Fast and easy way to build a custom search experience in you app.
  search_page: ^2.0.0+1
  # Masked text input for flutter.
  flutter_masked_text2:
    git:
      url: git://github.com/Flutter-Fox/flutter_masked_text.git
      ref: hotfix-0.9.1
  # Flutter plugin for sharing content via the platform share UI,6
  # using the ACTION_SEND intent on Android and UIActivityViewController on iOS.
  share_plus: ^3.0.4
  # a widget provided to the flutter scroll component drop-down refresh and pull up load.
  pull_to_refresh: ^2.0.0
  # A library useful for creating fuzzy timestamps. (e.g. "15 minutes ago")
  timeago: ^3.1.0
  # Flutter plugin for launching a URL. Supports web, phone, SMS, and email schemes.
  url_launcher: ^6.0.16
  # A carousel slider widget, support infinite scroll and custom child widget.
  carousel_slider: ^4.0.0
  # A wrapper around Ably's Cocoa and Java client library SDKs, providing iOS and Android support.
  ably_flutter: ^1.2.6

dependency_overrides:
  provider: ^6.0.1
  flutter_svg: "0.23.0+1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  # bloc_test: ^8.1.0
  logger: ^1.0.0
  flutter_launcher_icons: ^0.9.1
  flutter_native_splash: ^1.3.1
  # Pedantic lints your whole project strictly
  # Pedantic does a great job keeping the project with similar code styles
  pedantic: ^1.11.1
  # Code Generators
  build_runner: ^2.1.4
  freezed: ^1.0.0
  injectable_generator: ^1.5.2
  built_value_generator: ^8.1.3
  auto_route_generator: ^3.1.0
  retrofit_generator:
    git:
      url: git://github.com/Flutter-Fox/retrofit.dart.git
      ref: trevorwang-master
      path: generator/
  json_serializable: ^6.0.1
  floor_generator:
    git:
      url: git://github.com/Flutter-Fox/floor.git
      ref: ft/require-freezed
      path: floor_generator/

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/logo/
    - assets/images/dashboard/
    - assets/images/onboarding/
    - assets/images/dashboard/avatars/
    - assets/svgs/
    - assets/svgs/auth/
    - assets/svgs/onboarding/
    - assets/svgs/dashboard/
    - assets/svgs/logo/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
    - family: WashryteIcon
      fonts:
        - asset: assets/fonts/WashryteIcon.ttf
